# Generated by Django 2.2.5 on 2020-04-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
                ('review_count', models.CharField(max_length=100)),
                ('is_open', models.CharField(max_length=100)),
                ('attributes', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('business_id', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('useful', models.CharField(max_length=100)),
                ('funny', models.CharField(max_length=100)),
                ('cool', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PREDICTION_CHART',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=100, null=True)),
                ('artistId', models.CharField(blank=True, max_length=200, null=True)),
                ('prediction', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('musicbrainzArtistId', models.CharField(blank=True, max_length=100, null=True)),
                ('artistName', models.CharField(blank=True, max_length=100, null=True)),
                ('musicbrainzTrackId', models.CharField(blank=True, max_length=100, null=True)),
                ('trackName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
