# Generated by Django 2.2.5 on 2020-04-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=100)),
                ('compliment_count', models.CharField(max_length=100)),
                ('business_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('review_count', models.CharField(max_length=100)),
                ('yelping_since', models.CharField(max_length=100)),
                ('friends', models.CharField(max_length=100)),
                ('useful', models.CharField(max_length=100)),
                ('funny', models.CharField(max_length=100)),
                ('cool', models.CharField(max_length=100)),
                ('fans', models.CharField(max_length=100)),
                ('elite', models.CharField(max_length=100)),
                ('average_stars', models.CharField(max_length=100)),
                ('compliment_hot', models.CharField(max_length=100)),
                ('compliment_more', models.CharField(max_length=100)),
                ('compliment_profile', models.CharField(max_length=100)),
                ('compliment_cute', models.CharField(max_length=100)),
                ('compliment_list', models.CharField(max_length=100)),
                ('compliment_note', models.CharField(max_length=100)),
                ('compliment_plain', models.CharField(max_length=100)),
                ('compliment_cool', models.CharField(max_length=100)),
                ('compliment_funny', models.CharField(max_length=100)),
                ('compliment_writer', models.CharField(max_length=100)),
                ('compliment_photos', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userData',
                'managed': False,
            },
        ),
    ]
